---
- name: Configure VMs
- hosts: all
  become: true
  roles:
    - user-setup
  # remote_user: root

- import_playbook: roles/user-setup/tasks/main.yml
- import_playbook: roles/ssh-keys/tasks/main.yml
- import_playbook: roles/fail2ban/tasks/main.yml
- import_playbook: roles/dns/tasks/main.yml
